version: '3.8'

services:
  api:
    build: .
    container_name: dr_fastapi_backend
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  frontend:
    build: .
    container_name: dr_streamlit_frontend
    command: streamlit run src/app_frontend.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/predict
    depends_on:
      - api
